import type { ConceptId, QuizQuestion } from "./types";

export const QUIZZES: Record<ConceptId, QuizQuestion[]> = {
  bayes: [
    {
      id: "b1",
      prompt: "Posterior is proportional to…",
      choices: ["Prior only", "Likelihood only", "Prior × likelihood", "1 − prior"],
      answer: 2,
      explain: "Bayes: posterior ∝ prior × likelihood (then normalize).",
    },
    {
      id: "b2",
      prompt: "A very rare disease (tiny prior) usually means…",
      choices: [
        "A positive test guarantees disease",
        "Posterior can stay modest even with a decent test",
        "Likelihood does not matter",
        "Prior equals posterior",
      ],
      answer: 1,
      explain: "Base rates matter — rare priors need strong evidence.",
    },
    {
      id: "b3",
      prompt: "If likelihood of data under H is zero…",
      choices: [
        "Posterior of H becomes 1",
        "Posterior of H becomes 0",
        "Prior doubles",
        "Nothing changes",
      ],
      answer: 1,
      explain: "Impossible data under H kills that hypothesis.",
    },
    {
      id: "b4",
      prompt: "Updating beliefs after seeing data is called…",
      choices: ["Regularization", "Inference / Bayesian updating", "Bagging", "Whitening"],
      answer: 1,
      explain: "We move from prior to posterior given the likelihood.",
    },
  ],
  clt: [
    {
      id: "c1",
      prompt: "The CLT is about the distribution of…",
      choices: ["A single draw", "Sample means (or sums)", "The population only", "Medians always"],
      answer: 1,
      explain: "Sampling distributions of means become approximately normal.",
    },
    {
      id: "c2",
      prompt: "As sample size n grows, the SE of the mean…",
      choices: ["Grows like n", "Shrinks like 1/√n", "Stays fixed", "Becomes the variance"],
      answer: 1,
      explain: "Var(mean) = σ²/n so SD scales as 1/√n.",
    },
    {
      id: "c3",
      prompt: "Even for a skewed population, large-n sample means…",
      choices: [
        "Stay equally skewed",
        "Often look more bell-shaped",
        "Become uniform",
        "Must be discrete",
      ],
      answer: 1,
      explain: "That’s the practical punchline of the CLT.",
    },
    {
      id: "c4",
      prompt: "CLT requires the draws to be…",
      choices: [
        "Always normal already",
        "Ideally i.i.d. with finite variance (roughly)",
        "Deterministic",
        "Sorted",
      ],
      answer: 1,
      explain: "Independence + finite variance are the classic conditions.",
    },
  ],
  "gradient-descent": [
    {
      id: "g1",
      prompt: "Gradient descent steps…",
      choices: [
        "Along +∇L",
        "Along −∇L",
        "Orthogonal to ∇L only",
        "Randomly forever",
      ],
      answer: 1,
      explain: "We descend, so we move opposite the gradient.",
    },
    {
      id: "g2",
      prompt: "A learning rate that is too large often…",
      choices: ["Always converges faster safely", "Oscillates or diverges", "Zeros the gradient", "Removes bias"],
      answer: 1,
      explain: "Overshooting the valley is a classic failure mode.",
    },
    {
      id: "g3",
      prompt: "At a local minimum of a smooth loss, ∇L is…",
      choices: ["Infinite", "≈ 0", "Equal to the learning rate", "Random"],
      answer: 1,
      explain: "Stationary points have vanishing gradient.",
    },
    {
      id: "g4",
      prompt: "Why animate the path, not just plot the surface?",
      choices: [
        "Surfaces are illegal",
        "You see step size / trajectory dynamics",
        "Animation changes the math",
        "Gradients cannot be computed",
      ],
      answer: 1,
      explain: "Intuition lives in how the point moves as lr changes.",
    },
  ],
  "bias-variance": [
    {
      id: "v1",
      prompt: "Very low polynomial degree tends to…",
      choices: ["Overfit", "Underfit (high bias)", "Zero train error always", "Ignore test data"],
      answer: 1,
      explain: "Too simple → systematic error (bias).",
    },
    {
      id: "v2",
      prompt: "Very high degree on noisy data tends to…",
      choices: ["High bias", "Low train error, high test error (variance)", "Perfect generalization", "Linear fits"],
      answer: 1,
      explain: "Flexible models chase noise.",
    },
    {
      id: "v3",
      prompt: "The sweet spot on the U-shaped test curve is…",
      choices: ["Degree 0 only", "A middle complexity balancing bias and variance", "Infinite degree", "No training"],
      answer: 1,
      explain: "Bias–variance tradeoff in one picture.",
    },
    {
      id: "v4",
      prompt: "Train MSE falling while test MSE rises suggests…",
      choices: ["Underfitting", "Overfitting", "Perfect CLT", "Bayesian prior"],
      answer: 1,
      explain: "Classic overfit signature.",
    },
  ],
  roc: [
    {
      id: "r1",
      prompt: "Raising the positive threshold usually…",
      choices: [
        "Increases recall, decreases precision",
        "Decreases false positives (often lower recall)",
        "Does nothing",
        "Always improves AUC",
      ],
      answer: 1,
      explain: "Stricter threshold → fewer predicted positives.",
    },
    {
      id: "r2",
      prompt: "Recall (TPR) is…",
      choices: ["TP/(TP+FP)", "TP/(TP+FN)", "TN/(TN+FP)", "FP/(FP+TN)"],
      answer: 1,
      explain: "Of all actual positives, how many did we catch?",
    },
    {
      id: "r3",
      prompt: "ROC plots…",
      choices: ["Precision vs degree", "TPR vs FPR across thresholds", "Loss vs lr", "Prior vs posterior"],
      answer: 1,
      explain: "Each threshold is a point on the ROC curve.",
    },
    {
      id: "r4",
      prompt: "AUC close to 0.5 means…",
      choices: ["Perfect ranking", "Near-random ranking", "Zero false positives", "Infinite precision"],
      answer: 1,
      explain: "0.5 ≈ coin flip ranking quality.",
    },
  ],
};
